//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace esoft.entitis
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbEntities : DbContext
    {
        public DbEntities()
            : base("name=DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DealSet> DealSet { get; set; }
        public virtual DbSet<DemandSet> DemandSet { get; set; }
        public virtual DbSet<PersonSet> PersonSet { get; set; }
        public virtual DbSet<PersonSet_Agent> PersonSet_Agent { get; set; }
        public virtual DbSet<PersonSet_Client> PersonSet_Client { get; set; }
        public virtual DbSet<RealEstateFilterSet> RealEstateFilterSet { get; set; }
        public virtual DbSet<RealEstateFilterSet_ApartmentFilter> RealEstateFilterSet_ApartmentFilter { get; set; }
        public virtual DbSet<RealEstateFilterSet_HouseFilter> RealEstateFilterSet_HouseFilter { get; set; }
        public virtual DbSet<RealEstateFilterSet_LandFilter> RealEstateFilterSet_LandFilter { get; set; }
        public virtual DbSet<RealEstateSet> RealEstateSet { get; set; }
        public virtual DbSet<RealEstateSet_Apartment> RealEstateSet_Apartment { get; set; }
        public virtual DbSet<RealEstateSet_House> RealEstateSet_House { get; set; }
        public virtual DbSet<RealEstateSet_Land> RealEstateSet_Land { get; set; }
        public virtual DbSet<SupplySet> SupplySet { get; set; }
    }
}
