//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace esoft.entitis
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealEstateFilterSet_LandFilter
    {
        public Nullable<double> MinArea { get; set; }
        public Nullable<double> MaxArea { get; set; }
        public int Id { get; set; }
    
        public virtual RealEstateFilterSet z3_RealEstateFilterSet { get; set; }
    }
}
