//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace esoft.entitis
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealEstateSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RealEstateSet()
        {
            this.z3_SupplySet = new HashSet<SupplySet>();
        }
    
        public int Id { get; set; }
        public string Address_City { get; set; }
        public string Address_Street { get; set; }
        public string Address_House { get; set; }
        public string Address_Number { get; set; }
        public Nullable<double> Coordinate_latitude { get; set; }
        public Nullable<double> Coordinate_longitude { get; set; }
        public string Adress
        {
            get
            {
                return (Address_City + "," + Address_Street + "," + Address_House + "," + Address_Number).ToString();
            }
        }
        public int Proverka
        {
            get
            {
                if (z3_RealEstateSet_House != null)
                {
                    return 1;
                }
                else if (z3_RealEstateSet_Apartment != null)
                {
                    return 2;
                }
                else  
                {
                    return 3;
                }
            }
        }
        public virtual RealEstateSet_Apartment z3_RealEstateSet_Apartment { get; set; }
        public virtual RealEstateSet_House z3_RealEstateSet_House { get; set; }
        public virtual RealEstateSet_Land z3_RealEstateSet_Land { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplySet> z3_SupplySet { get; set; }
    }
}
