//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace esoft.entitis
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplySet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupplySet()
        {
            this.z3_DealSet = new HashSet<DealSet>();
        }
    
        public int Id { get; set; }
        public long Price { get; set; }
        public Nullable<int> AgentId { get; set; }
        public int ClientId { get; set; }
        public int RealEstateId { get; set; }
        
        public string Predlozenie
        {
            get
            {
                return ("|" + Id + "|" + z3_RealEstateSet.Adress).ToString();
            }
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DealSet> z3_DealSet { get; set; }
        public virtual PersonSet_Agent z3_PersonSet_Agent { get; set; }
        public virtual PersonSet_Client z3_PersonSet_Client { get; set; }
        public virtual RealEstateSet z3_RealEstateSet { get; set; }
    }
}
